/**
 * Lightweight built-in translation system.
 * Drop-in replacement for useTranslation() from react-i18next.
 * Uses Zustand settings store for language persistence.
 */
import { useSettingsStore } from '../stores/useSettingsStore';

export type Lang = 'en' | 'fr' | 'ar';

const translations: Record<Lang, Record<string, string>> = {
  en: {
    eventPro: 'Event Pro',
    signIn: 'Sign In',
    signUp: 'Create Account',
    email: 'Email',
    password: 'Password',
    name: 'Full Name',
    noAccount: "Don't have an account?",
    haveAccount: 'Already have an account?',
    createOne: 'Create one',
    upcoming: 'Upcoming',
    events: 'Events',
    noEventsTitle: 'No Events Yet',
    noEventsBody: 'Be the first to create something amazing for your community.',
    createFirst: '+ Create First Event',
    newEvent: 'New Event',
    createEvent: 'Create Event',
    newLabel: 'NEW',
    editingLabel: 'EDITING',
    eventTitle: 'Event Title',
    description: 'Description',
    date: 'Date',
    time: 'Time',
    location: 'Location',
    coverPhoto: 'Cover Photo',
    tapToUpload: 'Tap to upload a cover image',
    publish: 'Publish Event',
    saveChanges: 'Save Changes',
    about: 'About this Event',
    register: 'Register for this Event',
    edit: 'Edit',
    back: 'Back',
    profile: 'Profile',
    account: 'Account',
    settings: 'Settings',
    myRegistrations: 'My Registrations',
    notifications: 'Notifications',
    language: 'Language',
    appearance: 'Appearance',
    darkMode: 'Dark Mode',
    signOut: 'Sign out',
    proMember: '✦  Pro Member',
    explore: 'Explore',
  },
  fr: {
    eventPro: 'Event Pro',
    signIn: 'Se connecter',
    signUp: 'Créer un compte',
    email: 'E-mail',
    password: 'Mot de passe',
    name: 'Nom complet',
    noAccount: 'Pas de compte ?',
    haveAccount: 'Déjà un compte ?',
    createOne: 'Créer un',
    upcoming: 'À venir',
    events: 'Événements',
    noEventsTitle: 'Aucun événement',
    noEventsBody: 'Soyez le premier à créer quelque chose d\'incroyable.',
    createFirst: '+ Créer le premier',
    newEvent: 'Nouvel événement',
    createEvent: 'Créer un événement',
    newLabel: 'NOUVEAU',
    editingLabel: 'MODIFICATION',
    eventTitle: 'Titre de l\'événement',
    description: 'Description',
    date: 'Date',
    time: 'Heure',
    location: 'Lieu',
    coverPhoto: 'Photo de couverture',
    tapToUpload: 'Appuyez pour télécharger',
    publish: 'Publier l\'événement',
    saveChanges: 'Enregistrer',
    about: 'À propos',
    register: 'S\'inscrire à cet événement',
    edit: 'Modifier',
    back: 'Retour',
    profile: 'Profil',
    account: 'Compte',
    settings: 'Paramètres',
    myRegistrations: 'Mes inscriptions',
    notifications: 'Notifications',
    language: 'Langue',
    appearance: 'Apparence',
    darkMode: 'Mode sombre',
    signOut: 'Se déconnecter',
    proMember: '✦  Membre Pro',
    explore: 'Explorer',
  },
  ar: {
    eventPro: 'إيفنت برو',
    signIn: 'تسجيل الدخول',
    signUp: 'إنشاء حساب',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    name: 'الاسم الكامل',
    noAccount: 'ليس لديك حساب؟',
    haveAccount: 'لديك حساب بالفعل؟',
    createOne: 'أنشئ واحداً',
    upcoming: 'القادمة',
    events: 'الفعاليات',
    noEventsTitle: 'لا توجد فعاليات',
    noEventsBody: 'كن أول من يُنشئ شيئاً رائعاً لمجتمعك.',
    createFirst: '+ أنشئ أول فعالية',
    newEvent: 'فعالية جديدة',
    createEvent: 'إنشاء فعالية',
    newLabel: 'جديد',
    editingLabel: 'تعديل',
    eventTitle: 'عنوان الفعالية',
    description: 'الوصف',
    date: 'التاريخ',
    time: 'الوقت',
    location: 'المكان',
    coverPhoto: 'صورة الغلاف',
    tapToUpload: 'اضغط لرفع صورة',
    publish: 'نشر الفعالية',
    saveChanges: 'حفظ التغييرات',
    about: 'عن هذه الفعالية',
    register: 'سجّل في هذه الفعالية',
    edit: 'تعديل',
    back: 'رجوع',
    profile: 'الملف الشخصي',
    account: 'الحساب',
    settings: 'الإعدادات',
    myRegistrations: 'تسجيلاتي',
    notifications: 'الإشعارات',
    language: 'اللغة',
    appearance: 'المظهر',
    darkMode: 'الوضع المظلم',
    signOut: 'تسجيل الخروج',
    proMember: '✦  عضو مميز',
    explore: 'استكشف',
  },
};

/** Drop-in replacement for useTranslation() */
export const useT = () => {
  const language = useSettingsStore(s => s.language) as Lang;
  const dict = translations[language] ?? translations.en;
  const t = (key: string) => dict[key] ?? key;
  return { t, language, isRTL: language === 'ar' };
};

export const LANGUAGES = [
  { code: 'en', label: 'English', flag: '🇺🇸' },
  { code: 'fr', label: 'Français', flag: '🇫🇷' },
  { code: 'ar', label: 'العربية', flag: '🇸🇦', rtl: true },
];
